### ISSUE TITLE
Not all changed files staged and committed

### ISSUE THREAD

**Issue by SRFU-NN** [mbarkhau/bumpver#218] opened 2023-08-07 13:14 UTC
I have an issue where bumpver doesn't stage and commit all of the changes it has made. As best I can tell, it fails when there is capital letters in a folder name on the path to a file.

Reproduction steps:
1. Fetch https://github.com/SRFU-NN/test_bumpver/tree/main/src (minimal example)
2. Create a virtual environment
3. Install bumpver version 2023.1125
4. Run `bumpver update --patch `

Expected results:
All 4 copies of test.txt have updated version, and are included in the tagged commit.

Actual result:
Three copies of test.txt has updated version and are included in the tagged commit.
`src\CaPiTaLiZaTiOn\test.txt` has updated version, but is not staged.

Environment:
Windows 10 Enterprise, Version 10.0.19044 Build 19044
Python 3.9.4
bumpver version 2023.1125

**Comment by mbarkhau** [comment] 2023-08-07 22:43
Thank you for this report. I imagine this is a duplicate of #204.

**Comment by mbarkhau** [comment] 2023-08-08 11:11
Yes, I've closed it. If you can help to figure out how to fix this, I'd greatly appreciate it.

**Closed by mbarkhau** 2023-08-08 11:11 UTC

**Comment by SRFU-NN** [comment] 2023-08-08 12:15
A quick test indicates that pathlib does not have the same issue as pathlib2 – though I know going to an unsupported package is not a good idea.

I will investigate some more.

Best regards
Søren Furbo
Automation Scientist
7660 Automation and Process Optimisation
+45 3079 0427 (direct) ǀ  ***@***.******@***.***>

**Comment by SRFU-NN** [comment] 2023-08-08 13:30
I have created an issue in pathlib2: https://github.com/jazzband/pathlib2/issues/86

**Comment by mbarkhau** [comment] 2023-08-08 15:44
@SRFU-NN I'd like to somehow test the changes in PR #219. Since we don't have windows in our CI system, perhaps you can help with this? Can you review PR #219 ?

**Comment by SRFU-NN** [comment] 2023-08-09 11:24
> @SRFU-NN I'd like to somehow test the changes in PR #219. Since we don't have windows in our CI system, perhaps you can help with this? Can you review PR #219 ?

I'll look into it.
